<%
  elasticsearch_host = nil
  if_link("elasticsearch") { |elasticsearch_link|
    elasticsearch_host = elasticsearch_link.instances[0].address
  }
  unless elasticsearch_host
    elasticsearch_host = p("elastalert.es_host")
  end
%>
---
rules_folder: /var/vcap/store/praeco/rules
<%= YAML.dump(JSON.load(JSON.dump({"run_every": p("elastalert.run_every")}))).gsub("---\n", '').strip %>
<%= YAML.dump(JSON.load(JSON.dump({"buffer_time": p("elastalert.buffer_time")}))).gsub("---\n", '').strip %>
es_host: <%= elasticsearch_host %>
es_port: <%= p("elastalert.es_port") %>
writeback_index: <%= p("elastalert.writeback_index") %>
<%= YAML.dump(JSON.load(JSON.dump({"alert_time_limit": p("elastalert.alert_time_limit")}))).gsub("---\n", '').strip %>
