---
name: praeco
releases:
- name: praeco
  version: latest
  #url: https://github.com/making/openjdk-boshrelease/releases/download/8.0.2/openjdk-boshrelease-8.0.2.tgz
  #sha1: e76b73d2560d143b155e958aa06a2e266e261464

stemcells:
- os: ubuntu-xenial
  alias: xenial
  version: latest

instance_groups:
- name: praeco
  jobs:
  - name: node
    release: praeco
  - name: elastalert-server
    release: praeco
    properties:
      foo:
        bar: baz
  instances: 1
  stemcell: xenial
  update:
    max_in_flight: 1
    serial: true
  azs:
  - z1
  - z2
  - z3
  vm_type: default
  persistent_disk: 1024
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
