---
name: praeco
releases:
- name: praeco
  version: ((praeco_version))
  url: https://github.com/daichi703n/praeco-boshrelease/releases/download/((praeco_version))/praeco-boshrelease-((praeco_version)).tgz
  sha1: ((praeco_sha1))
- name: elastalert
  version: latest
- name: nginx
  version: latest

stemcells:
- os: ubuntu-jammy
  alias: jammy
  version: latest

instance_groups:
- name: praeco
  jobs:
  - name: elastalert
    release: elastalert
    properties:
      elastalert:
        es_host: ((es_host))
        es_port: ((es_port))
        rules: []
  - name: nginx
    release: nginx
    properties:
      nginx_conf: "events { worker_connections 1024; }"
  - name: elastalert-server
    release: praeco
    properties:
      elastalert:
        es_host: ((es_host))
        es_port: ((es_port))
        writeback_index: praeco_elastalert_status
  - name: praeco
    release: praeco
    properties:
      praeco:
        external_url: ((praeco_external_url))
        slack_webhook_url: ((slack_webhook_url))
  instances: 1
  stemcell: jammy
  update:
    max_in_flight: 1
    serial: true
  azs:
  - z1
  - z2
  - z3
  vm_type: default
  persistent_disk: 1024
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-100000
  update_watch_time: 5000-100000
