---
name: praeco
releases:
- name: praeco
  version: latest
- name: elastalert
  version: latest

stemcells:
- os: ubuntu-xenial
  alias: xenial
  version: latest

instance_groups:
- name: praeco
  jobs:
  - name: elastalert
    release: elastalert
    properties:
      elastalert:
        es_host: h-cent-doc01.designet.local
        es_port: 9200
        rules: []
  - name: elastalert-server
    release: praeco
    properties:
      elastalert:
        es_host: h-cent-doc01.designet.local
        es_port: 9200
        writeback_index: praeco_elastalert_status
  - name: praeco
    release: praeco
    properties:
      elastalert:
        es_host: h-cent-doc01.designet.local
        es_port: 9200
        writeback_index: praeco_elastalert_status
  instances: 1
  stemcell: xenial
  update:
    max_in_flight: 1
    serial: true
  azs:
  - z1
  - z2
  - z3
  vm_type: default
  persistent_disk: 1024
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-100000
  update_watch_time: 5000-100000
