#ops-file for collocate with elastic-stack-bosh-deployment
#https://github.com/bosh-elastic-stack/elastic-stack-bosh-deployment

- type: replace
  path: /releases/-
  value:
    name: praeco
    version: ((praeco_version))
    url: https://github.com/daichi703n/praeco-boshrelease/releases/download/((praeco_version))/praeco-boshrelease-0.1.0.tgz
    sha1: ((praeco_sha1))

- type: replace
  path: /instance_groups/name=praeco?
  value:
    name: praeco
    jobs:
    - name: elastalert
      release: elastalert
      properties:
        elastalert:
          es_host: ((es_host))
          es_port: ((es_port))
          rules: []
    - name: nginx
      release: nginx
      properties:
        nginx_conf: "events { worker_connections 1024; }"
    - name: elastalert-server
      release: praeco
      properties:
        elastalert:
          es_host: ((es_host))
          es_port: ((es_port))
          writeback_index: praeco_elastalert_status
    - name: praeco
      release: praeco
      properties:
        praeco:
          external_url: ((praeco_external_url))
          slack_webhook_url: ((slack_webhook_url))
    instances: 1
    stemcell: jammy
    update:
      max_in_flight: 1
      serial: true
    azs:
    - ap-northeast-1a
    - ap-northeast-1c
    - ap-northeast-1d
    vm_type: t2.small
    vm_extensions:
    - spot-instance-t2-small
    - praeco-lb
    persistent_disk: 1024
    networks:
    - name: bosh